server:
   port: 8888
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
           native:
              searchLocations: file:///C:/Loblaw/Learning/TransServices/prasjai-configuration-service/src/main/resources/config
